import fs from "node:fs/promises";
const DATA_FILE=new URL("../data/events.json",import.meta.url);
const SOURCES=[
{key:"dallas",city:"Dallas",venue:"Kay Bailey Hutchison Convention Center Dallas",url:"https://www.dallasconventioncenter.com/events",parser:"dallas"},
{key:"miami",city:"Miami Beach",venue:"Miami Beach Convention Center",url:"https://www.miamibeachconvention.com/events",parser:"miami"},
{key:"sandiego",city:"San Diego",venue:"San Diego Convention Center",url:"https://www.visitsandiego.com/calendar?page=1",parser:"sandiego"},
{key:"anaheim",city:"Anaheim",venue:"Anaheim Convention Center",url:"https://www.visitanaheim.org/listing/anaheim-convention-center/2959/amp/",parser:"anaheim"},
{key:"orlando",city:"Orlando",venue:"Orange County Convention Center",url:"https://events.occc.net/",parser:"orlando"},
{key:"vegas",city:"Las Vegas",venue:"Las Vegas Convention Center",url:"https://www.vegasmeansbusiness.com/destination-calendar/",parser:"generic"},
{key:"chicago",city:"Chicago",venue:"McCormick Place",url:"https://www.mccormickplace.com/events/",parser:"generic"},
{key:"nyc",city:"New York",venue:"Jacob K. Javits Convention Center",url:"https://www.javitscenter.com/calendar/",parser:"generic"}
];
const MONTHS={jan:1,january:1,feb:2,february:2,mar:3,march:3,apr:4,april:4,may:5,jun:6,june:6,jul:7,july:7,aug:8,august:8,sep:9,sept:9,september:9,oct:10,october:10,nov:11,november:11,dec:12,december:12};
const pad=n=>String(n).padStart(2,"0"),iso=(y,m,d)=>`${y}-${pad(m)}-${pad(d)}`,month=s=>MONTHS[String(s||"").replace(/\./g,"").toLowerCase()]||null,clean=s=>String(s||"").replace(/\s+/g," ").trim();
const decode=s=>String(s||"").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&ndash;/gi,"–").replace(/&mdash;/gi,"—");
function textLines(html){return decode(String(html).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,"\n").replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,"\n").replace(/<(br|hr)\b[^>]*\/?>/gi,"\n").replace(/<\/?(p|div|li|section|article|h[1-6]|time|tr|td|th|a|button)\b[^>]*>/gi,"\n").replace(/<[^>]+>/g," ")).split(/\n+/).map(clean).filter(Boolean)}
function parseNamedRange(s){const x=clean(s);let m=x.match(/^([A-Za-z]{3,9})\.?\s+(\d{1,2})(?:,\s*(\d{4}))?\s*[-–]\s*(?:([A-Za-z]{3,9})\.?\s+)?(\d{1,2})(?:,\s*)?(\d{4})$/i);if(m){const m1=month(m[1]),m2=month(m[4])||m1,y2=+m[6];if(!m1||!m2)return null;let y1=m[3]?+m[3]:y2;if(!m[3]&&m1>m2)y1--;return{startDate:iso(y1,m1,+m[2]),endDate:iso(y2,m2,+m[5])}}m=x.match(/^([A-Za-z]{3,9})\.?\s+(\d{1,2})(?:,\s*|\s+)(\d{4})$/i);if(m){const mo=month(m[1]);if(!mo)return null;const d=iso(+m[3],mo,+m[2]);return{startDate:d,endDate:d}}return null}
function parseNumeric(s){const m=String(s).match(/(\d{1,2})\/(\d{1,2})\/(\d{4})/);return m?iso(+m[3],+m[1],+m[2]):null}
function normalize(e,s){return{title:clean(e.title),city:s.city,venue:e.venue||s.venue,startDate:e.startDate,endDate:e.endDate||e.startDate,category:clean(e.category||"Convention Center Event"),attendance:e.attendance?Number(e.attendance):null,sourceKey:s.key,sourceUrl:e.sourceUrl||s.url}}
function usefulTitle(s){const x=clean(s);return x.length>2&&x.length<190&&!/^(learn more|event website|view more|calendar|events|all events|upcoming events|grid|list|cal|search|filter|load more events)$/i.test(x)}
function jsonLdEvents(html,s){const out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const root=JSON.parse(m[1]),stack=Array.isArray(root)?[...root]:[root];while(stack.length){const x=stack.pop();if(!x||typeof x!=="object")continue;if(Array.isArray(x)){stack.push(...x);continue}if(x["@graph"])stack.push(x["@graph"]);if(x.itemListElement)stack.push(x.itemListElement);if(x.item)stack.push(x.item);const t=x["@type"],isEvent=Array.isArray(t)?t.includes("Event"):t==="Event";if(isEvent&&x.name&&x.startDate){const d1=String(x.startDate).slice(0,10),d2=String(x.endDate||x.startDate).slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(d1))out.push(normalize({title:x.name,startDate:d1,endDate:d2,category:"Event",sourceUrl:x.url||s.url},s))}}}catch{}}return out}
function parseDallas(html,s){const lines=textLines(html),out=[],cats=new Set(["Consumer Show","Sporting Event","Meeting","Special Event","Trade Show"]);for(let i=0;i<lines.length;i++){const r=parseNamedRange(lines[i]);if(!r)continue;let j=i+1,category="";if(cats.has(lines[j]))category=lines[j++];while(j<Math.min(lines.length,i+7)&&!usefulTitle(lines[j]))j++;if(j<lines.length&&usefulTitle(lines[j]))out.push(normalize({title:lines[j],category,...r},s))}return out}
function parseMiami(html,s){const lines=textLines(html),out=[];for(let i=0;i<lines.length;i++){const d1=parseNumeric(lines[i]);if(!d1)continue;let j=i+1,d2=d1;const maybe=parseNumeric(lines[j]);if(maybe){d2=maybe;j++}while(j<Math.min(lines.length,i+7)&&!usefulTitle(lines[j]))j++;if(j<lines.length&&usefulTitle(lines[j])&&!/summer black business showcase/i.test(lines[j]))out.push(normalize({title:lines[j],startDate:d1,endDate:d2},s))}return out}
function parseSanDiego(html,s){const lines=textLines(html),out=[];for(let i=0;i<lines.length;i++){const a=lines[i].match(/^Attendance:\s*(--|[\d,]+)$/i);if(!a)continue;const title=lines[i-1];if(!usefulTitle(title)||/^Private Event:/i.test(title))continue;const summary=lines[i+1]||"",ds=[...summary.matchAll(/(\d{2})\/(\d{2})\/(\d{4})/g)];if(ds.length<2)continue;const startDate=iso(+ds[0][3],+ds[0][1],+ds[0][2]),endDate=iso(+ds[1][3],+ds[1][1],+ds[1][2]);let category=summary.slice(title.length,ds[0].index).trim()||"Convention Center Event";const attendance=a[1]==="--"?null:Number(a[1].replace(/,/g,""));out.push(normalize({title,startDate,endDate,category,attendance},s))}return out}
function parseAnaheim(html,s){const lines=textLines(html),out=[];for(let i=0;i<lines.length;i++){const m=lines[i].match(/^Dates vary between\s+(.+?)\s+[-–]\s+(.+)$/i);if(!m)continue;const left=parseNamedRange(m[1]),right=parseNamedRange(m[2]);if(!left||!right)continue;let title="";for(let j=i-1;j>=Math.max(0,i-7);j--){if(/^(Presented By:|Location:)/i.test(lines[j]))continue;if(usefulTitle(lines[j])){title=lines[j];break}}if(title)out.push(normalize({title,startDate:left.startDate,endDate:right.startDate,category:"Convention Center Event"},s))}return out}
async function fetchText(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 ConventionCalendarBot/1.0","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"},signal:controller.signal,redirect:"follow"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
async function parseOrlando(s){const html=await fetchText(s.url);let out=jsonLdEvents(html,s);if(out.length)return out;const candidateMaps=new Set(["https://events.occc.net/sitemap.xml","https://events.occc.net/sitemap_index.xml"]);try{const robots=await fetchText("https://events.occc.net/robots.txt");for(const m of robots.matchAll(/^\s*Sitemap:\s*(https?:\/\/\S+)/gmi))candidateMaps.add(m[1])}catch{}const eventUrls=new Set(),queue=[...candidateMaps];for(let pass=0;pass<3&&queue.length;pass++){const batch=queue.splice(0,8);for(const mapUrl of batch){try{const xml=await fetchText(mapUrl);for(const m of xml.matchAll(/<loc>\s*(https?:\/\/[^<]+)\s*<\/loc>/gi)){const u=decode(m[1]);if(/events\.occc\.net\/event\//i.test(u))eventUrls.add(u);else if(/sitemap/i.test(u)&&queue.length<30)queue.push(u)}}catch{}}}const urls=[...eventUrls].slice(-120);for(let i=0;i<urls.length;i+=8){const batch=await Promise.allSettled(urls.slice(i,i+8).map(async u=>({u,html:await fetchText(u)})));for(const r of batch){if(r.status!=="fulfilled")continue;let items=jsonLdEvents(r.value.html,{...s,url:r.value.u});if(items.length){out.push(...items);continue}const lines=textLines(r.value.html),dateIndex=lines.findIndex(x=>/^Dates:\s*/i.test(x));let range=null;if(dateIndex>=0)range=parseNamedRange(lines[dateIndex].replace(/^Dates:\s*/i,""))||parseNamedRange(lines[dateIndex+1]||"");const title=(lines.find(x=>usefulTitle(x)&&!/^Dates:?$/i.test(x))||"").replace(/^#\s*/,"");if(range&&title)out.push(normalize({title,...range},{...s,url:r.value.u}))}}return out}
function parseGeneric(html,s){const structured=jsonLdEvents(html,s);if(structured.length)return structured;const lines=textLines(html),out=[];for(let i=0;i<lines.length;i++){const r=parseNamedRange(lines[i]);if(!r)continue;for(let j=i+1;j<Math.min(lines.length,i+5);j++){if(usefulTitle(lines[j])){out.push(normalize({title:lines[j],...r},s));break}}}return out}
function dedupe(items){const seen=new Set();return items.filter(e=>{if(!e.title||!e.startDate)return false;const k=`${e.sourceKey}|${e.startDate}|${e.title.toLowerCase()}`;if(seen.has(k))return false;seen.add(k);return true})}
function upcoming(items){const today=new Date().toISOString().slice(0,10),max=new Date(Date.now()+550*86400000).toISOString().slice(0,10);return items.filter(e=>(e.endDate||e.startDate)>=today&&e.startDate<=max)}
async function refreshSource(s){try{let events=[];if(s.parser==="orlando")events=await parseOrlando(s);else if(s.parser==="miami"){const pages=await Promise.allSettled(Array.from({length:7},(_,i)=>fetchText(i?`${s.url}?page=${i}`:s.url)));for(const p of pages)if(p.status==="fulfilled")events.push(...parseMiami(p.value,s))}else{const html=await fetchText(s.url);if(s.parser==="dallas")events=parseDallas(html,s);else if(s.parser==="sandiego")events=parseSanDiego(html,s);else if(s.parser==="anaheim")events=parseAnaheim(html,s);else events=parseGeneric(html,s)}events=dedupe(upcoming(events));if(!events.length)throw new Error("No parsable upcoming events returned");return{ok:true,events,error:null}}catch(err){return{ok:false,events:[],error:String(err?.message||err)}}}
const previous=JSON.parse(await fs.readFile(DATA_FILE,"utf8"));let combined=[];const statuses=[];for(const s of SOURCES){const r=await refreshSource(s),old=(previous.events||[]).filter(e=>e.sourceKey===s.key);combined.push(...(r.ok?r.events:upcoming(old)));const prev=(previous.sources||[]).find(x=>x.key===s.key);statuses.push({key:s.key,city:s.city,venue:s.venue,url:s.url,ok:r.ok,lastSuccess:r.ok?new Date().toISOString():(prev?.lastSuccess||null),error:r.ok?null:r.error});console.log(`${s.city}: ${r.ok?`${r.events.length} events`:`fallback (${r.error})`}`)}combined=dedupe(upcoming(combined)).sort((a,b)=>a.startDate.localeCompare(b.startDate)||(Number(b.attendance||0)-Number(a.attendance||0)));await fs.writeFile(DATA_FILE,JSON.stringify({updatedAt:new Date().toISOString(),events:combined,sources:statuses},null,2)+"\n");console.log(`Wrote ${combined.length} upcoming events.`);
